"use client";
import { useState } from "react";

export default function CalculatorPage() {
  const [form, setForm] = useState({
    revenue: "", cogs: "", operating_expenses: "",
    owners_salary: "", owners_benefits: "", one_time_expenses: "",
    industry: "other", business_price: "", down_payment_pct: "10",
    annual_net_income: ""
  });
  const [results, setResults] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const handle = (e: any) => setForm({ ...form, [e.target.name]: e.target.value });

  const calculate = async () => {
    setLoading(true);
    const [valRes, loanRes] = await Promise.all([
      fetch("http://localhost:8000/api/calculator/valuate", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          revenue: +form.revenue, cogs: +form.cogs,
          operating_expenses: +form.operating_expenses,
          owners_salary: +form.owners_salary,
          owners_benefits: +form.owners_benefits,
          one_time_expenses: +form.one_time_expenses,
          industry: form.industry
        })
      }),
      fetch("http://localhost:8000/api/calculator/loan", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          business_price: +form.business_price,
          down_payment_pct: +form.down_payment_pct / 100,
          annual_net_income: +form.annual_net_income
        })
      })
    ]);
    const val = await valRes.json();
    const loan = await loanRes.json();
    setResults({ val, loan });
    setLoading(false);
  };

  const fmt = (n: number) => "$" + n.toLocaleString();

  const exportPDF = () => {
    const { jsPDF } = require("jspdf");
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    doc.setFontSize(20);
    doc.setTextColor(29, 78, 216);
    doc.text("SBA Business Valuation Report", 20, 25);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on ${date} | sba-platform.vercel.app`, 20, 33);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 37, 190, 37);

    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text("Business Valuation", 20, 48);

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    doc.text(`Seller's Discretionary Earnings (SDE): ${fmt(results.val.sde)}`, 20, 58);
    doc.text(`Industry: ${results.val.industry} (${results.val.valuation.multiple_used}x multiple)`, 20, 66);
    doc.text(`Valuation Range:`, 20, 74);
    doc.text(`  Low:  ${fmt(results.val.valuation.low)}`, 25, 82);
    doc.text(`  Mid:  ${fmt(results.val.valuation.mid)}`, 25, 90);
    doc.text(`  High: ${fmt(results.val.valuation.high)}`, 25, 98);

    doc.line(20, 105, 190, 105);

    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text("SBA 7(a) Loan Summary", 20, 116);

    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    doc.text(`Business Price:    ${fmt(results.loan.loan.business_price)}`, 20, 126);
    doc.text(`Down Payment:      ${fmt(results.loan.loan.down_payment)} (${results.loan.loan.down_payment_pct}%)`, 20, 134);
    doc.text(`Loan Amount:       ${fmt(results.loan.loan.loan_amount)}`, 20, 142);
    doc.text(`Interest Rate:     ${results.loan.loan.interest_rate}%`, 20, 150);
    doc.text(`Loan Term:         ${results.loan.loan.term_years} years`, 20, 158);
    doc.text(`Monthly Payment:   ${fmt(results.loan.loan.monthly_payment)}`, 20, 166);
    doc.text(`Total Interest:    ${fmt(results.loan.loan.total_interest)}`, 20, 174);

    doc.line(20, 181, 190, 181);

    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text("SBA Eligibility", 20, 192);

    doc.setFontSize(11);
    const eligible = results.loan.eligibility.eligible;
    doc.setTextColor(eligible ? 22 : 185, eligible ? 163 : 28, eligible ? 74 : 26);
    doc.text(eligible ? "✓ SBA Eligible" : "✗ Not SBA Eligible", 20, 202);

    if (results.loan.dscr) {
      doc.setTextColor(60, 60, 60);
      doc.text(`DSCR: ${results.loan.dscr.dscr} — ${results.loan.dscr.message}`, 20, 210);
    }

    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text("This report is for informational purposes only. Consult a financial advisor before making investment decisions.", 20, 270);
    doc.text("Generated by SBA Platform | sba-platform.vercel.app", 20, 278);

    doc.save(`sba-valuation-report-${date.replace(/\//g, "-")}.pdf`);
  };

  return (
    <main className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">SBA Business Valuation Calculator</h1>
        <p className="text-gray-500 mb-8">Enter business financials to get a valuation and SBA loan estimate</p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div className="bg-white rounded-xl shadow p-6">
            <h2 className="text-lg font-semibold mb-4 text-gray-800">Business Financials</h2>
            {[
              { label: "Annual Revenue", name: "revenue" },
              { label: "Cost of Goods Sold (COGS)", name: "cogs" },
              { label: "Operating Expenses", name: "operating_expenses" },
              { label: "Owner's Salary", name: "owners_salary" },
              { label: "Owner's Benefits", name: "owners_benefits" },
              { label: "One-Time Expenses", name: "one_time_expenses" },
            ].map(f => (
              <div key={f.name} className="mb-3">
                <label className="block text-sm text-gray-600 mb-1">{f.label}</label>
                <input type="number" name={f.name} value={(form as any)[f.name]}
                  onChange={handle} placeholder="0"
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
              </div>
            ))}
            <div className="mb-3">
              <label className="block text-sm text-gray-600 mb-1">Industry</label>
              <select name="industry" value={form.industry} onChange={handle}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
                {["restaurant","retail","service","healthcare","technology","manufacturing","construction","transportation","other"]
                  .map(i => <option key={i} value={i}>{i.charAt(0).toUpperCase() + i.slice(1)}</option>)}
              </select>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow p-6">
            <h2 className="text-lg font-semibold mb-4 text-gray-800">SBA Loan Details</h2>
            {[
              { label: "Business Asking Price", name: "business_price" },
              { label: "Annual Net Income", name: "annual_net_income" },
            ].map(f => (
              <div key={f.name} className="mb-3">
                <label className="block text-sm text-gray-600 mb-1">{f.label}</label>
                <input type="number" name={f.name} value={(form as any)[f.name]}
                  onChange={handle} placeholder="0"
                  className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
              </div>
            ))}
            <div className="mb-3">
              <label className="block text-sm text-gray-600 mb-1">Down Payment %</label>
              <input type="number" name="down_payment_pct" value={form.down_payment_pct}
                onChange={handle} min="10" max="30"
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
            </div>
          </div>
        </div>

        <button onClick={calculate} disabled={loading}
          className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 rounded-xl transition mb-8">
          {loading ? "Calculating..." : "Calculate Valuation & SBA Loan"}
        </button>

    
          {results && (
          <div>
          <button onClick={exportPDF}
            className="w-full mb-6 bg-green-600 hover:bg-green-700 text-white font-semibold py-3 rounded-xl transition flex items-center justify-center gap-2">
            ⬇ Download PDF Report
          </button>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white rounded-xl shadow p-6">
              <h2 className="text-lg font-semibold mb-4 text-gray-800">Business Valuation</h2>
              <p className="text-sm text-gray-500 mb-1">Seller's Discretionary Earnings (SDE)</p>
              <p className="text-2xl font-bold text-blue-600 mb-4">{fmt(results.val.sde)}</p>
              <div className="grid grid-cols-3 gap-2 text-center">
                {["low","mid","high"].map(k => (
                  <div key={k} className="bg-gray-50 rounded-lg p-3">
                    <p className="text-xs text-gray-400 uppercase">{k}</p>
                    <p className="font-bold text-gray-800">{fmt(results.val.valuation[k])}</p>
                  </div>
                ))}
              </div>
              <p className="text-xs text-gray-400 mt-3">Industry multiple: {results.val.valuation.multiple_used}x</p>
            </div>

            <div className="bg-white rounded-xl shadow p-6">
              <h2 className="text-lg font-semibold mb-4 text-gray-800">SBA 7(a) Loan</h2>
              {[
                { label: "Down Payment", val: results.loan.loan.down_payment },
                { label: "Loan Amount", val: results.loan.loan.loan_amount },
                { label: "Monthly Payment", val: results.loan.loan.monthly_payment },
                { label: "Total Interest", val: results.loan.loan.total_interest },
              ].map(r => (
                <div key={r.label} className="flex justify-between py-2 border-b border-gray-100">
                  <span className="text-sm text-gray-600">{r.label}</span>
                  <span className="font-semibold text-gray-900">{fmt(r.val)}</span>
                </div>
              ))}
              <div className={`mt-4 rounded-lg p-3 text-sm font-medium ${results.loan.eligibility.eligible ? "bg-green-50 text-green-700" : "bg-red-50 text-red-700"}`}>
                {results.loan.eligibility.eligible ? "✅ SBA Eligible" : "❌ " + results.loan.eligibility.issues[0]}
              </div>
              {results.loan.dscr && (
                <p className="text-xs text-gray-400 mt-2">DSCR: {results.loan.dscr.dscr} — {results.loan.dscr.message}</p>
              )}
            </div>
          </div>
        </div>
          </div>
        )}
      </div>
    </main>
  );
}
